// Generated by https://quicktype.io

export interface Cliente {
  id: number;
  firstName: string;
  lastName: string;
  phoneNumber: string;
  birthDate: string;
  createdAt: string;
  updatedAt: string;
  lastLogin: null;
  receiveAds: boolean;
  addresses: Address[];
  email: string;
}

export interface Address {
  id: string;
  state: string;
  city: string;
  addressLine1: string;
  addressLine2: string;
  addressReference: string;
  lat: number;
  lon: number;
  createdAt: string;
  updatedAt: string;
}
