// Generated by https://quicktype.io

import { Area } from "./area";
import { Schedule } from "./schedule";
import { Tag } from "./tag";

type AreaStore = Omit<Area, "coordinates">;

export interface Store {
  id: number;
  name: string;
  state: string;
  city: string;
  addressLine1: string;
  addressLine2: string | null;
  addressReference: string | null;
  phoneNumber: string;
  whatsappNumber: string | null;
  facebook: string | null;
  instagram: string | null;
  isDeliveryEnabled: boolean;
  isPickupEnabled: boolean;
  isTaxEnabled: boolean;
  isCashPaymentEnabled: boolean;
  isWompiPaymentEnabled: boolean;
  isDeliveryCostEnabled: boolean;
  isSchedulingEnabled: boolean;
  productException: boolean;
  lat: number;
  lon: number;
  deliveryCost: number | null | string;
  deliveryMin: number | null | string;
  defaultHomeTagCategory: Tag | null;
  whatsapp: string | null;
  schedules: Schedule[];
  altSchedules: any[];
  areas: AreaStore[];
  headerImage: string | null;
  headerUrl: string | null;
}

export type PreferenceFormValues = Omit<
  Store,
  | "id"
  | "whatsapp"
  | "areas"
  | "schedules"
  | "lat"
  | "lon"
  | "altSchedules"
  | "productException"
>;

export type StoreMutation = Omit<
  PreferenceFormValues,
  "defaultHomeTagCategory"
> & { defaultHomeTagCategoryId: number };
